definitions:
  models.Todo:
    properties:
      complete:
        type: boolean
      id:
        type: string
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is API for CRUD todo app
  title: Todo API With Swagger Documentation
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      - application/x-www-form-urlencoded
      description: get json array todo
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Todo'
            type: array
      summary: Show All Todo
      tags:
      - todo
swagger: "2.0"
